### ISSUE TITLE
Running 'branin' example produces: 'AssertionError: {'_log': <RootLogger root (INFO)>}'

### ISSUE THREAD

**Issue by felixkreuk** [automl/labwatch#17]
```
If you want to use BayesianOptimization you have to install the following dependencies:
https://github.com/automl/RoBO
george
RUNNING sampled configs
Traceback (most recent call last):
  File "1.py", line 6, in <module>
    ex.run(named_configs=['search_space'])
  File "/home/mlspeech/felixk/.local/share/virtualenvs/a-AaumlMlO/lib/python3.6/site-packages/sacred/experiment.py", line 208, in run
    meta_info, options)
  File "/home/mlspeech/felixk/.local/share/virtualenvs/a-AaumlMlO/lib/python3.6/site-packages/sacred/experiment.py", line 433, in _create_run
    None))
  File "/home/mlspeech/felixk/.local/share/virtualenvs/a-AaumlMlO/lib/python3.6/site-packages/sacred/initialize.py", line 368, in create_run
    ncfg_updates = scaff.run_named_config(cfg_name)
  File "/home/mlspeech/felixk/.local/share/virtualenvs/a-AaumlMlO/lib/python3.6/site-packages/sacred/initialize.py", line 92, in run_named_config
    fallback=self.fallback)
  File "/home/mlspeech/felixk/.local/share/virtualenvs/a-AaumlMlO/lib/python3.6/site-packages/labwatch/assistant.py", line 196, in _search_space_wrapper
    assert not fallback, "{}".format(fallback)
AssertionError: {'_log': <RootLogger root (INFO)>}
```

**Comment by totifra** [comment]
Hi there, too!
see #15

**Comment by felixkreuk** [comment]
Thanks @totifra ! 
I wonder why this isn't being pushed as a fix.
