### ISSUE TITLE
ValueError: The result of your experiment is a <class 'NoneType'> but labwatch expects either a number or a dict

### ISSUE THREAD

**Issue by SonicNight** [automl/labwatch#19]
Traceback (most recent call last):
  File "train_model.py", line 330, in <module>
    @ex.automain
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/sacred/experiment.py", line 137, in automain
    self.run_commandline()
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/sacred/experiment.py", line 260, in run_commandline
    return self.run(cmd_name, config_updates, named_configs, {}, args)
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/sacred/experiment.py", line 208, in run
    meta_info, options)
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/sacred/experiment.py", line 433, in _create_run
    None))
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/sacred/initialize.py", line 368, in create_run
    ncfg_updates = scaff.run_named_config(cfg_name)
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/sacred/initialize.py", line 92, in run_named_config
    fallback=self.fallback)
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/labwatch/assistant.py", line 203, in _search_space_wrapper
    values = self.get_suggestion()
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/labwatch/assistant.py", line 315, in get_suggestion
    self.update_optimizer()
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/labwatch/assistant.py", line 296, in update_optimizer
    for job in completed_jobs if job["_id"] not in self.known_jobs]
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/labwatch/assistant.py", line 296, in <listcomp>
    for job in completed_jobs if job["_id"] not in self.known_jobs]
  File "/home/ubuntu/miniconda3/envs/mongo/lib/python3.7/site-packages/labwatch/assistant.py", line 448, in convert_result
    "or a dict".format(type(result)))
ValueError: The result of your experiment is a <class 'NoneType'> but labwatch expects either a number or a dict

I'm getting the above error when I try to run my experiment. 

At the end of my main method, I have a line:
    results = dict()
    results["val_metric"] = some_value
    return results

which I believe is returning a dict. But I'm getting the error nonetheless...

**Comment by SonicNight** [comment]
The issue is in around line 298 of Assistant.py

"       info = [(self._clean_config(job["config"]), convert_result(job["result"]), job)
                for job in completed_jobs if job["_id"] not in self.known_jobs]  "

This line looks for completed jobs and tries to call convert_result.

My problem is that one of my previous jobs did not return anything. So when I tried to call it again, no matter what I returned, it still sees a previous job and believes that the result of the experiment is class NoneType
